inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - vendor/bundle/**/* # fix for running on Travis CI

#################### Layout ##############################

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

#################### Metrics ##############################

Metrics/BlockLength:
  ExcludedMethods:
    - describe

#################### RSpec ################################


RSpec/MultipleExpectations:
  Max: 3

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
