AllCops:
  Exclude:
    - 'auxiliary_rails.gemspec'

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
