AllCops:
  Exclude:
    - auxiliary_rails.gemspec
    - vendor/bundle/**/* # fix for running on Travis CI

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
