AllCops:
  Exclude:
    - auxiliary_rails.gemspec
    - vendor/bundle/**/* # fix for running on Travis CI

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
