inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/rspec
    - bin/rubocop
    - lib/generators/auxiliary_rails/templates/**/*
    - vendor/**/* # fix for CI
  NewCops: enable
  TargetRubyVersion: 2.5

#################### Layout ##############################

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

#################### Metrics ##############################

Metrics/BlockLength:
  IgnoredMethods:
    - describe

#################### RSpec ################################

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

#################### Style ###############################

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/NegatedIf:
  EnforcedStyle: postfix
